name: hurtle
version: 0.1.0.0

dependencies:
- base >= 4.7 && < 5
- containers
- megaparsec
- parser-combinators
- gloss
- gloss-juicy
- directory
- filepath

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wno-orphans 
- -Wno-missing-export-lists

language: GHC2021

default-extensions: LambdaCase

library:
  source-dirs:
    - src

executable: 
  main:                Main.hs
  source-dirs:         app
  ghc-options:
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N
  dependencies:
  - hurtle

tests:
  hurtle-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hurtle
    - tasty
    - tasty-hunit
    - tasty-quickcheck
    - tasty-reporter-muffled
    - random
    - ansi-terminal
    - QuickCheck
    - containers
    - cryptohash-md5
    - bytestring
    - directory
    - filepath
